apiVersion: v1
kind: Service
metadata:
  name: {{ include "healthchecks-proxy.fullname" . }}
  labels:
{{ include "healthchecks-proxy.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodeport }}
  selector:
    app.kubernetes.io/name: {{ include "healthchecks-proxy.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
