name: Healthchecks Proxy Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --deploy --ignore-pipfile  
    - name: Login to DockerHub
      env:
        USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: docker login -u $USERNAME -p $PASSWORD
    - name: Build Docker Image
      env:
        $USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      run: docker build . --file Dockerfile --tag $USERNAME/healthchecks-proxy:$GITHUB_REF
      
    - name: Push to DockerHub
      run: docker push adenau/healthchecks-proxy:$GITHUB_REF
